instrumentation:
    root: .
    extensions:
        - .js
    default-excludes: true
    excludes: ['sample/*','sample/*.js','sample/test/*.js','sample/lib/*.js','**min.js','gulpfile.js']
    include-all-sources: true